### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by okj203** [pauulkim/paultrails#2]
- [x] Photos table might need a foreign key of a park since a park has many photos. Photos belong to a trail, trail to park, but do all photos belong to a trail? Consider if there will be photos that only belong to a park, but not a trail.
- [x] In the MVP list, the tails portion is described with `hikes`. Choose either the word trail or hike.
- [x] Reviews sample state says hike_id, but reviews table says trail_id. Choose either the word trail or hike.
- [x] Photos sample state says hike_id, but photos table says trail_id. Choose either the word trail or hike.
- [x] Parks table needs location data (longitude and latitude) for it to be used with Google Maps API.
- [x] Sample state is part of the frontend JS; use camelCase.
- [x] Search bar component is missing.
- [x] In the frontend routes, trail item component should be nested under trail index component.
- [x] In the frontend routes, review item should be nested under review index.

**Comment by paulwkim** [comment]
All items resolved!

**Comment by okj203** [comment]
Good job!
